---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - export NODEJS_VERSION=18
    - ln -s /opt/alt/alt-nodejs$NODEJS_VERSION/root/usr/bin/node ~/bin/node
    - ln -s /opt/alt/alt-nodejs$NODEJS_VERSION/root/usr/bin/npm ~/bin/npm
    - npm ci --production=false
    - npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
    - find $DEPLOYPATH -name "*.map" -delete