---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$(whoami)/public_html/
    - export NODEJS_VERSION=18
    - ln -s /opt/alt/alt-nodejs$NODEJS_VERSION/root/usr/bin/node ~/bin/node || true
    - ln -s /opt/alt/alt-nodejs$NODEJS_VERSION/root/usr/bin/npm ~/bin/npm || true
    - npm ci --production=false
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH
    - find $DEPLOYPATH -name "*.map" -delete